import mongoose from 'mongoose';
import Recommendation, {
  IRecommendation,
  RecommendationStatus,
  RecommendationType,
} from '../models/Recommendation.model';
import AuditLog from '../models/AuditLog.model';
import Resource from '../models/Resource.model';
import { ApiError } from '../utils/ApiError';
import * as resourceService from './resource.service';
import { getIO, ROOMS } from '../config/socket';

export interface CreateRecommendationInput {
  incidentId: mongoose.Types.ObjectId | string;
  type: RecommendationType;
  targetHospitalId: mongoose.Types.ObjectId | string;
  patientIds?: (mongoose.Types.ObjectId | string)[];
  resourceRequests?: { type: string; quantity: number }[];
  explanation: string[];
  confidence: number;
}

export interface ActionResult {
  resourceType: string;
  requested: number;
  reserved: number;
  success: boolean;
  detail: string;
}

export interface ApprovalResult {
  recommendation: IRecommendation;
  siblingsRejected: number;
  actionResults: ActionResult[];
}

async function writeAudit(
  userId: string,
  action: string,
  entityType: string,
  entityId: mongoose.Types.ObjectId | string,
  previousValue: unknown,
  newValue: unknown,
  reason?: string
): Promise<void> {
  await AuditLog.create({
    userId: new mongoose.Types.ObjectId(userId),
    action,
    entityType,
    entityId,
    previousValue,
    newValue,
    reason,
  });
}

function emitRecommendationEvent(
  recommendation: IRecommendation,
  extra: Record<string, unknown> = {}
): void {
  try {
    const io = getIO();
    io.to(ROOMS.adminDashboard).emit('recommendation-updated', {
      recommendation,
      ...extra,
      updatedAt: new Date(),
    });
  } catch {
    // Socket layer not initialized — audit log remains the source of truth.
  }
}

export const createRecommendation = async (
  input: CreateRecommendationInput,
  userId: string
): Promise<IRecommendation> => {
  if (!Array.isArray(input.explanation) || input.explanation.length === 0) {
    throw ApiError.badRequest('Every recommendation requires a non-empty explanation array');
  }

  const recommendation = await Recommendation.create({
    incidentId: input.incidentId,
    type: input.type,
    targetHospitalId: input.targetHospitalId,
    patientIds: input.patientIds ?? [],
    resourceRequests: input.resourceRequests ?? [],
    explanation: input.explanation,
    confidence: input.confidence,
    status: 'pending',
    humanApprovalRequired: true,
  });

  await writeAudit(
    userId,
    'recommendation.created',
    'Recommendation',
    recommendation._id,
    null,
    { status: 'pending', type: recommendation.type, confidence: recommendation.confidence },
    'Generated by EmergencyFlow allocation engine — human approval required'
  );

  emitRecommendationEvent(recommendation, { event: 'created' });
  return recommendation;
};

export const getRecommendations = async (filter: {
  incidentId?: string;
  status?: RecommendationStatus;
  type?: RecommendationType;
}): Promise<IRecommendation[]> => {
  const query: Record<string, unknown> = {};
  if (filter.incidentId && mongoose.Types.ObjectId.isValid(filter.incidentId)) {
    query.incidentId = new mongoose.Types.ObjectId(filter.incidentId);
  }
  if (filter.status) query.status = filter.status;
  if (filter.type) query.type = filter.type;

  return Recommendation.find(query)
    .sort({ createdAt: -1 })
    .limit(100)
    .populate('targetHospitalId', 'name code traumaLevel')
    .populate('incidentId', 'eventType severity status predictedArrivals');
};

export const getRecommendationById = async (id: string): Promise<IRecommendation> => {
  const recommendation = await Recommendation.findById(id)
    .populate('targetHospitalId', 'name code traumaLevel')
    .populate('incidentId', 'eventType severity status predictedArrivals')
    .populate('approvedBy', 'name role');
  if (!recommendation) throw ApiError.notFound('Recommendation not found');
  return recommendation;
};

async function executeResourceActions(
  recommendation: IRecommendation,
  userId: string
): Promise<ActionResult[]> {
  const results: ActionResult[] = [];

  for (const request of recommendation.resourceRequests) {
    let remaining = request.quantity;
    const docs = await Resource.find({
      hospitalId: recommendation.targetHospitalId,
      type: request.type,
    }).sort({ available: -1 });

    for (const doc of docs) {
      if (remaining <= 0) break;
      const take = Math.min(doc.available, remaining);
      if (take <= 0) continue;

      const previous = { available: doc.available, reserved: doc.reserved };
      try {
        await resourceService.reserveResource(String(doc._id), take);
        remaining -= take;
        await writeAudit(
          userId,
          'resource.reserved',
          'Resource',
          doc._id,
          previous,
          { available: doc.available - take, reserved: doc.reserved + take },
          `Committed by approved recommendation ${recommendation._id}`
        );
      } catch (err) {
        await writeAudit(
          userId,
          'resource.reserve_failed',
          'Resource',
          doc._id,
          previous,
          previous,
          `Failed while executing recommendation ${recommendation._id}: ${(err as Error).message}`
        );
      }
    }

    const reserved = request.quantity - remaining;
    results.push({
      resourceType: request.type,
      requested: request.quantity,
      reserved,
      success: remaining === 0,
      detail:
        remaining === 0
          ? `Reserved ${reserved} ${request.type} at target hospital`
          : `Only ${reserved}/${request.quantity} ${request.type} could be reserved — manual follow-up needed`,
    });
  }

  return results;
}

export const approveRecommendation = async (
  id: string,
  userId: string
): Promise<ApprovalResult> => {
  const recommendation = await Recommendation.findById(id);
  if (!recommendation) throw ApiError.notFound('Recommendation not found');

  if (recommendation.status !== 'pending') {
    throw ApiError.conflict(
      `Only pending recommendations can be approved (current status: ${recommendation.status})`
    );
  }

  const previous = { status: recommendation.status, approvedBy: recommendation.approvedBy };
  recommendation.status = 'approved';
  recommendation.approvedBy = new mongoose.Types.ObjectId(userId);
  await recommendation.save();

  await writeAudit(
    userId,
    'recommendation.approved',
    'Recommendation',
    recommendation._id,
    previous,
    { status: 'approved', approvedBy: userId },
    'Human-in-the-loop approval'
  );

  // Auto-reject sibling pending recommendations for the same incident.
  const siblings = await Recommendation.find({
    incidentId: recommendation.incidentId,
    _id: { $ne: recommendation._id },
    status: 'pending',
  });
  for (const sibling of siblings) {
    sibling.status = 'rejected';
    await sibling.save();
    await writeAudit(
      userId,
      'recommendation.auto_rejected',
      'Recommendation',
      sibling._id,
      { status: 'pending' },
      { status: 'rejected' },
      `Auto-rejected because recommendation ${recommendation._id} was approved for the same incident`
    );
    emitRecommendationEvent(sibling, { event: 'auto_rejected' });
  }

  // Commit resources only after human approval.
  const actionResults = await executeResourceActions(recommendation, userId);

  emitRecommendationEvent(recommendation, { event: 'approved', actionResults });

  return {
    recommendation,
    siblingsRejected: siblings.length,
    actionResults,
  };
};

export const overrideRecommendation = async (
  id: string,
  userId: string,
  reason: string
): Promise<IRecommendation> => {
  if (!reason || reason.trim().length < 5) {
    throw ApiError.badRequest('Override reason is mandatory (minimum 5 characters)');
  }

  const recommendation = await Recommendation.findById(id);
  if (!recommendation) throw ApiError.notFound('Recommendation not found');

  if (recommendation.status !== 'pending') {
    throw ApiError.conflict(
      `Only pending recommendations can be overridden (current status: ${recommendation.status})`
    );
  }

  const previous = { status: recommendation.status, overrideReason: recommendation.overrideReason };
  recommendation.status = 'overridden';
  recommendation.overrideReason = reason.trim();
  await recommendation.save();

  await writeAudit(
    userId,
    'recommendation.overridden',
    'Recommendation',
    recommendation._id,
    previous,
    { status: 'overridden', overrideReason: recommendation.overrideReason },
    reason.trim()
  );

  emitRecommendationEvent(recommendation, { event: 'overridden' });
  return recommendation;
};
